In [1]:
import numpy as np

In [2]:
import array

In [3]:
np.array ([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [5]:
np.array ([1,2,3,4,5,"parag",6+6j])

array(['1', '2', '3', '4', '5', 'parag', '(6+6j)'], dtype='<U64')

In [6]:
np.array([[1,4],[4,5]])

array([[1, 4],
       [4, 5]])

In [9]:
np.array([[1,4],[4,5,6]])

C:\Users\Milan\AppData\Local\Temp\ipykernel_24068\3075439275.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,4],[4,5,6]])


array([list([1, 4]), list([4, 5, 6])], dtype=object)

In [7]:
np.array([[[1,2,3,4,5]]])

array([[[1, 2, 3, 4, 5]]])

In [8]:
np.array([1,2,3],ndmin=3)

array([[[1, 2, 3]]])

In [14]:
a=np.array([(1,2,3),(4,5,6),(7,8,9)])

In [15]:
a[1][1]

5

In [16]:
a[1][1]=500

In [17]:
a

array([[  1,   2,   3],
       [  4, 500,   6],
       [  7,   8,   9]])

In [19]:
b = np.copy(a)

In [20]:
b

array([[  1,   2,   3],
       [  4, 500,   6],
       [  7,   8,   9]])

In [21]:
np.fromfunction(lambda i, j:i==j, (4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [22]:
np.fromfunction(lambda i, j:i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [23]:
np.fromiter(range(5) , dtype = int)

array([0, 1, 2, 3, 4])

In [24]:
np.fromstring('1,2,3,4',sep = ',', dtype = int)

array([1, 2, 3, 4])

In [25]:
type(a)

numpy.ndarray

In [26]:
a.ndim

2

In [27]:
a.size

9

In [28]:
a.shape

(3, 3)

In [30]:
np.linspace(3,8)

array([3.        , 3.10204082, 3.20408163, 3.30612245, 3.40816327,
       3.51020408, 3.6122449 , 3.71428571, 3.81632653, 3.91836735,
       4.02040816, 4.12244898, 4.2244898 , 4.32653061, 4.42857143,
       4.53061224, 4.63265306, 4.73469388, 4.83673469, 4.93877551,
       5.04081633, 5.14285714, 5.24489796, 5.34693878, 5.44897959,
       5.55102041, 5.65306122, 5.75510204, 5.85714286, 5.95918367,
       6.06122449, 6.16326531, 6.26530612, 6.36734694, 6.46938776,
       6.57142857, 6.67346939, 6.7755102 , 6.87755102, 6.97959184,
       7.08163265, 7.18367347, 7.28571429, 7.3877551 , 7.48979592,
       7.59183673, 7.69387755, 7.79591837, 7.89795918, 8.        ])

In [31]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [1]:
import numpy as np

In [2]:
import array

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.zeros((3,5,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [6]:
np.ones((3,5,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [7]:
np.zeros((2,5,4))+5

array([[[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]],

       [[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]]])

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])